TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += environmentmonitor.db
DB += environmentmonitor.proto

#=======================================
include $(TOP)/configure/RULES
