TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += envmon_common.db
DB += envmon_sensor.db
DB += error_setter.db
DATA += environmentmonitor.proto

#=======================================
include $(TOP)/configure/RULES
