TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += environmentmonitor.db
DATA += environmentmonitor.proto

#=======================================
include $(TOP)/configure/RULES
